spring.application.name=SistemaRestaurante
server.port=${PORT:8080}

#CONEXION A LA BASE DE DATOS
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/sistemaReservasRestaurante}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#CONFIGURACION JPA
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=true

#DIALECTO
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

#CLAVE JWT
jwt.secret=${JWT_SECRET:sistemaRestauranteAF-y9poS(XFM]pYrcJDg(M;q;E%HVz0)w8E8}
